main: pl.pickaxe.largesk.LargeSk
name: LargeSk
version: 0.5
description: An addon for Skript with some cool features.
author: Nicofisi
website: http://github.com/Nicofisi/LargeSk
depend: [Skript]
softdepend: [AAC]
