main: pl.pickaxe.largesk.LargeSk
name: LargeSk
version: 1.0.2
description: An addon for Skript with some cool features.
author: Nicofisi
website: http://github.com/Nicofisi/LargeSk
depend: [Skript]
softdepend: [AAC]
loadbefore: [Umbaska]

commands:
  largesk:
    description: Main command of LargeSk
    usage: /lsk
    aliases: lsk
    
permissions:
  largesk.command.help:
    default: false
  largesk.command.info:
    default: false
  largesk.command.check:
    default: false
  largesk.command.update:
    default: false
  largesk.command.reload:
    default: false
  largesk.command.debug:
    default: false
  largesk.command.*:
    children:
      largesk.command.help: false
      largesk.command.check: false
      largesk.command.update: false
      largesk.command.reload: false
      largesk.command.debug: false
  largesk.*:
    children:
      largesk.command.*: false
